### ISSUE TITLE
Playlist sync fails when switching users

### ISSUE THREAD

**Issue by not-just-jack** [cmathews393/spotify-to-plex#35]
I have 4 managed users in Plex. The main users syncs all spotify playlists, the second users syncs about half the playlists, and the third, fourth, and fifth users don't have any that sync.

This is running on unraid. A screenshot of my container is below. 

![image](https://github.com/user-attachments/assets/1eb5491e-fc96-4aeb-a5d5-c0bf833a9f1d)

The plex usernames were copied from my plex admin account with a , in between each username. No spaces. 

I've also attached the log from the last job.
[log.txt](https://github.com/user-attachments/files/17115162/log.txt)

Let me know if there is anything else I can provide or if you see anything wrong. Thanks.

**Comment by cmathews393** [comment]
Oh I know what the problem is. I am not sure why the second user doesn't sync everything, but the reason the third + users aren't syncing is because its trying to auth with the current user, which in the case of rotating through the users is user2, which doesn't have the required permissions to impersonate user3. I thought I fixed this a while ago, but I'll take a look at see what happened.

**Comment by not-just-jack** [comment]
Thanks! 

In the interim, I have everyone syncing is separate containers...lol

**Comment by cmathews393** [comment]
Are you on the latest version of the docker image? There are log messages that should be showing up that aren't.
